name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Install Playwright Browsers
        run: npx playwright install chrome --with-deps

      - name: Run Playwright tests
        run: npx bddgen && npx playwright test
        env:
          BASE_URL: ${{ vars.BASE_URL || 'https://playwright.dev' }}
          LOG_LEVEL: info
          CI: true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Configure AWS credentials
        if: ${{ !cancelled() }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload Playwright reports to S3
        if: ${{ !cancelled() }}
        run: |
          aws s3 cp playwright-report/ s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive

      - name: Report URL
        if: ${{ !cancelled() }}
        run: |
          echo 'Playwright report: http://${{ secrets.S3_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com'
